name: Diagnostics

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  diagnostics:
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    strategy:
      matrix:
        branch: [
            #
            'current-pr',
            'next',
            # 'main',
          ]
        node-start: ['18.x']
        os: [ubuntu-latest]

    continue-on-error: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ matrix.branch == 'current-pr' && github.head_ref || matrix.branch }}

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: pnpm-store-${{github.head_ref}}-${{ matrix.branch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{github.head_ref}}-${{ matrix.branch }}-

      - run: pnpm install --child-concurrency 3
      - run: pnpm build

      - run: mkdir diagnostics-results
      - run: cd ./examples/.test/diagnostics-big-router && pnpm tsc --extendedDiagnostics && pnpm tsc --extendedDiagnostics > ./../../../diagnostics-results/diagnostics-${{ matrix.branch }}.txt
      - run: cat ./diagnostics-results/diagnostics-${{ matrix.branch }}.txt
      - name: Upload diagnostics results
        uses: actions/upload-artifact@v2
        with:
          name: diagnostics-results
          path: ./diagnostics-results

  comment:
    needs: diagnostics
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Download diagnostics results
        uses: actions/download-artifact@v2
        with:
          name: diagnostics-results
          path: diagnostics-results

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: pnpm-store-${{ github.head_ref }}-current-pr-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ github.head_ref }}-current-pr

      - run: pnpm install --child-concurrency 3

      - run: pnpm exec tsx .github/workflows/diagnosticsCompare.ts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
