name: autofix.ci # for "security reasons", this has to be named autofix.ai
permissions:
  contents: read
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  autofix:
    name: 'Lint and auto-fix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.event.pull_request.head.repo.fork && github.token || secrets.TRPC_GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-all-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-all-

      - name: Install deps (with cache)
        run: pnpm install --child-concurrency 3

      - name: Run ts-prune
        run: pnpm lint-prune

      # <autofixing>
      - run: pnpm turbo lint -- --fix
        if: ${{ failure() || success() }}
      - run: pnpm manypkg fix
        if: ${{ failure() || success() }}
      - run: pnpm format-fix
        if: ${{ failure() || success() }}
      # </autofixing>

      # commit autofixes
      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
        if: ${{ failure() || success() }}
        with:
          commit-message: 'chore: apply lint and formatting fixes'
          fail-fast: false
