name: autofix.ci # for "security reasons", this has to be named autofix.ai
permissions:
  contents: read

on:
  workflow_run:
    workflows: ['lint']
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  autofix:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-all-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-all-

      - name: Install deps (with cache)
        run: pnpm install --child-concurrency 3

      # - run: pnpm turbo lint -- --fix
      #   continue-on-error: true
      # - run: pnpm manypkg fix
      #   continue-on-error: true
      - run: pnpm format-fix
        continue-on-error: true

      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
