name: subtree-matrix
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync-downstream:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        path: [
            #
            next-prisma-starter,
            next-prisma-websockets-starter,
            next-prisma-todomvc,
            next-minimal-starter,
            next-big-router,
            minimal,
            minimal-react,
            .experimental/next-formdata,
            .experimental/next-app-dir,
          ]

    name: Update downstream ${{ matrix.path }} package

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run find-and-replace to remove '.experimental/' from above paths
        uses: mad9000/actions-find-and-replace-string@4
        id: findandreplace
        with:
          source: ${{ matrix.path }}
          find: '.experimental/'
          replace: ''
      - name: Get the above output
        run: echo "The replaced value is ${{ steps.findandreplace.outputs.value }}"

      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies and create separate lockfile
        run: |
          echo "shared-workspace-lockfile=false" >> .npmrc
          echo "link-workspace-packages=false" >> .npmrc
          cp ./pnpm-lock.yaml ./examples/${{ matrix.path }}/pnpm-lock.yaml
          pnpm install --no-frozen-lockfile

      - name: Commit changes
        run: |
          git config --global user.email "<>"
          git config --global user.name "trpc-bot"
          git add .
          git commit -m "chore: sync lockfile"

      - name: Sync downstream
        uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'trpc/examples-${{ steps.findandreplace.outputs.value }}'
          path: 'examples/${{ matrix.path }}'
          deploy_key: ${{ secrets.TRPC_DEPLOY_TOKEN }}
          force: true # will force push to the downstream repository
          branch: main # will push to the main branch of the downstream repository
